name: Install dagger from source
description:
# Expects a PAT named 'GH_PAT' in Actions secrets


inputs:
  dagger-git-ref:
    description: 'The dagger branch, tag or SHA to checkout.'
    default: 'main'
    required: true
  dagger-repo:
    description: 'The dagger repo (or fork) to checkout.'
    default: 'dagger/dagger'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout dagger at ref
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.inputs.dagger-repo }}
        path: 'src/dagger'
        ref: ${{ github.event.inputs.dagger-git-ref }}
        token: ${{ secrets.GH_PAT }}
        fetch-depth: 0
      
    # get SHA hash in case branch or tag was used for checkout
    - name: Get dagger git ref hash
      id: dagger-git-ref
      shell: bash
      run: |
        cd ${{ github.workspace }}/src/dagger
        echo "::set-output name=hash::$(git rev-parse HEAD)"
        
    - name: Install go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Cache dagger binary
      id: cache-dagger-binary
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/src/dagger/cmd/dagger/dagger
        key: ${{ runner.os }}-cache-dagger-binary-${{ steps.dagger-git-ref.outputs.hash }}
       
    - name: Build dagger
      if: steps.cache-dagger-binary.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cd ${{ github.workspace }}/src/dagger
        make dagger
